spring:
  application:
    name: signature-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

app:
  security:
    token: ${APP_TOKEN:test-token}
    signature:
      secret: ${SIGNATURE_SECRET:test-secret}

logging:
  level:
    root: INFO
    com.paysonix: DEBUG
    org.springframework.web: INFO

info:
  app:
    name: Signature Service
    description: Service for generating HMAC SHA256 signatures from form parameters
    version: 0.0.1-SNAPSHOT
    java:
      version: ${java.version}
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    version: ${project.version}
    time: ${build.time} 